import {
  ReactFlow,
  Background,
  Controls,
  MiniMap,
  Handle,
  Position,
  useNodesState,
  useEdgesState,
  useReactFlow,
  ReactFlowProvider,
  useNodesInitialized,
  Panel,
} from "@xyflow/react";

import { useEffect, useState } from "react";

import "@xyflow/react/dist/style.css";

import ProductNode from "./ProductNode";

import { autoLayout } from "../../../utils/production/autoLayout";

function RecipeNode({ data }) {
  return (
    <div className="production-node recipe-node">
      <Handle type="target" position={Position.Left} id="input" />

      <div className="recipe-node-title">{data.name}</div>

      <div className="recipe-node-runs">Runs: {formatNumber(data.runs)}</div>

      <div className="recipe-node-section">
        <strong>Inputs</strong>

        {Object.entries(data.inputs || {}).map(([product, amount]) => (
          <div key={product} className="recipe-row">
            <span>{product}</span>
            <span>{formatNumber(amount)}</span>
          </div>
        ))}
      </div>

      <div className="recipe-node-section">
        <strong>Outputs</strong>

        {Object.entries(data.outputs || {}).map(([product, amount]) => (
          <div key={product} className="recipe-row">
            <span>{product}</span>
            <span>{formatNumber(amount)}</span>
          </div>
        ))}
      </div>

      <Handle type="source" position={Position.Right} id="output" />
    </div>
  );
}

const nodeTypes = {
  product: ProductNode,
  recipe: RecipeNode,
};

function ProductionGraphInner({ initialNodes, initialEdges, graphId }) {
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);

  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);

  const [layoutVersion, setLayoutVersion] = useState(0);

  const { fitView } = useReactFlow();

  const nodesInitialized = useNodesInitialized();

  const [needsAutoLayout, setNeedsAutoLayout] = useState(false);

  useEffect(() => {
    setNodes(initialNodes);
    setEdges(initialEdges);

    if (initialNodes.length > 0) {
      setNeedsAutoLayout(true);
    }
  }, [graphId, initialNodes, initialEdges, setNodes, setEdges]);

  useEffect(() => {
    if (!needsAutoLayout || !nodesInitialized || nodes.length === 0) {
      return;
    }

    async function layout() {
      try {
        const layoutedNodes = await autoLayout(nodes, edges, "RIGHT");

        setNodes(layoutedNodes);

        setNeedsAutoLayout(false);

        requestAnimationFrame(() => {
          fitView({
            padding: 0.2,
            duration: 500,
          });
        });
      } catch (error) {
        console.error("Failed to auto layout production graph:", error);
      }
    }

    layout();
  }, [
    needsAutoLayout,
    nodesInitialized,
    nodes.length,
    edges,
    setNodes,
    fitView,
  ]);

  /*
   * Replace nodes when a new production graph is
   * generated by the planner.
   */
  useEffect(() => {
    setNodes(initialNodes);
  }, [initialNodes, setNodes]);

  /*
   * Replace edges when a new production graph is
   * generated.
   */
  useEffect(() => {
    setEdges(initialEdges);
  }, [initialEdges, setEdges]);

  async function handleAutoLayout() {
    if (!nodes.length) {
      return;
    }

    try {
      const layoutedNodes = await autoLayout(nodes, edges, "RIGHT");

      setNodes(layoutedNodes);

      /*
       * Wait until React Flow applies the new positions.
       */
      requestAnimationFrame(() => {
        fitView({
          padding: 0.2,
          duration: 500,
        });
      });
    } catch (error) {
      console.error("Failed to auto layout production graph:", error);
    }
  }

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      nodeTypes={nodeTypes}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      fitView
      minZoom={0.1}
      maxZoom={2}
      nodesDraggable
      nodesConnectable={false}
      elementsSelectable
    >
      <Background />

      <Controls />

      <MiniMap
        nodeColor={(node) => {
          switch (node.type) {
            case "recipe":
              return "#2563eb";

            case "product":
              if (node.data?.source === "buy") {
                return "#f59e0b";
              }

              if (node.data?.source === "raw") {
                return "#64748b";
              }

              return "#22c55e";

            default:
              return "#ffffff";
          }
        }}
        nodeStrokeWidth={0}
        maskColor="rgba(0, 0, 0, 0.5)"
        style={{
          width: 200,
          height: 150,
          background: "#FCFCFC",
        }}
      />

      <Panel position="top-right">
        <button
          type="button"
          className="auto-layout-button"
          onClick={handleAutoLayout}
          disabled={nodes.length === 0}
        >
          ↻ Auto Layout
        </button>
      </Panel>
    </ReactFlow>
  );
}

export default function ProductionGraph({ nodes, edges }) {
  return (
    <div className="production-graph">
      <ReactFlowProvider>
        <ProductionGraphInner
          initialNodes={nodes}
          initialEdges={edges}
          graphId={nodes.map((node) => node.id).join("|")}
        />
      </ReactFlowProvider>
    </div>
  );
}

function formatNumber(value) {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    return "0";
  }

  return Number(value.toFixed(3)).toLocaleString();
}
